#!/usr/bin/env python

"""Verify account login works on specified hosts."""

import pexpect
import sys, getpass, os
##Added to enable passing a file with servers listed - EG
import fileinput

USAGE = '''./login-chk file_containing_hosts'''
COMMAND_PROMPT = '[$#] '
TERMINAL_PROMPT = r'Terminal type\?'
TERMINAL_TYPE = 'xterm'
SSH_NEWKEY = r'Are you sure you want to continue connecting \(yes/no\)\?'

def login(host, user, password):

    child = pexpect.spawn('ssh -o StrictHostKeyChecking=no -ql %s %s' % (user, host))
    i = child.expect([pexpect.TIMEOUT, SSH_NEWKEY, '[Pp]assword: ', pexpect.EOF], timeout=20)
    if i == 0 or i == 3: # Timeout or EOF
        return None
    if i == 1: # SSH does not have the public key. Just accept it.
        child.sendline('yes')
        j = child.expect([pexpect.TIMEOUT, '[Pp]assword: '], timeout=20)
        if j == 0: # Timeout
            return None
    if i == 2:
        child.sendline(password)
    # Now we should be at the command prompt or are being asked for our terminal type
    i = child.expect(['Permission denied', pexpect.TIMEOUT,
                      TERMINAL_PROMPT, COMMAND_PROMPT], timeout=20)
    if i == 0:
        return None
    if i == 1:
        child.sendline('echo responsive-p')
        j = child.expect([pexpect.TIMEOUT, 'responsive-p'], timeout=20)
        if j == 0:
            return None
        elif j == 1:
            return child
    if i == 2:
        child.sendline(TERMINAL_TYPE)
        j = child.expect([pexpect.TIMEOUT, COMMAND_PROMPT], timeout=20)
        if j == 0:
            child.sendline('echo responsive-p')
            k = child.expect([pexpect.TIMEOUT, 'responsive-p'], timeout=20)
            if k == 0:
                return None
            elif k == 1:
                return child
        elif j == 1:
            return child
    if i == 3:
        return child

def main():

    if len(sys.argv) <= 1:
        print USAGE
        return 1

    user = raw_input('Username: ')
    while 1 == 1:
        password = getpass.getpass('Password: ')
        passwordconfirm = getpass.getpass('Confirm Password: ')
        if password == passwordconfirm:
            break
        print 'Passwords do not match.'

##    for host in sys.argv[1:]:
##Added the ability to pass a file with hosts - EG
    for host in fileinput.input(sys.argv[1:]):
        child = login(host, user, password)
        if child == None:
            print 'Could not login to: ', host
        else:
            print 'Successfully logged in to: ', host
            child.sendline('exit')

if __name__ == '__main__':
    try:
        main()
    except pexpect.ExceptionPexpect, e:
        print str(e)

